### ISSUE TITLE
Please add Mobile Ads SDK

### ISSUE THREAD

**Issue by MarvinFrankenfeld** [thisisthekap/Xamarin.FirebaseSlim.iOS#1]
https://developers.google.com/admob/ios/quick-start?hl=de

**Comment by thisisthekap** [comment]
@MarvinFrankenfeld

This is a slim binding. It is not a binding of full SDKs.

So not the SDKs itself are bound, but the XCode project in this repository. This XCode project is mapping the SDK calls to something which is easy to bind.

Please add the things needed to the XCode project, to extend the binding. Feel free to reach out to me on [Discord](https://discordapp.com/users/thekap#4353) if you need assistance on it.
